HotelManagement/Customers/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'customers'

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('customers/home/', home, name='home'),
    path('customer_login/', customer_login, name='login'),
    path('customer_logout/', customer_logout, name='logout'),

    path('management_login/', management_login_page, name='management_login_page'),

    path('add_email/<email>', add_email, name='add-email-to-notifications')
]

HotelManagement/FoodManagement/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'food_management'

urlpatterns = [
    path('food_management/home/', home, name='home'),
    path('food_management/login/', food_management_login, name='login'),
    path('logout/', food_management_logout, name='logout'),
]

HotelManagement/HotelManagement/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Customers.urls')),
    path('', include('RoomService.urls')),
    path('', include('RoomsManagement.urls')),
    path('', include('FoodService.urls')),
    path('', include('FoodManagement.urls')),
]+staticfiles_urlpatterns()

HotelManagement/RoomsManagement/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'rooms_management'

urlpatterns = [
    path('room_management/home/', home, name='home'),
    path('room_management/login/', room_management_login, name='login'),
    path('logout/', room_management_logout, name='logout'),
]

HotelManagement/Customers/models.py
from django.db import models
from django.contrib.auth.models import User


# Gender Options...
gender_options = (
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Others'),
)


# Address...
class Address(models.Model):
    country = models.CharField(max_length=20, blank=False)
    state = models.CharField(max_length=30, blank=False)
    city = models.CharField(max_length=30, blank=False)
    street = models.CharField(max_length=40, blank=False)
    house_number = models.CharField(max_length=20, blank=False)

    def __str__(self):
        return self.country + ', ' + self.city


# Contact_Details...
class ContactDetails(models.Model):
    phone_number = models.BigIntegerField()
    email = models.EmailField()

    def __str__(self):
        return self.email + ', ' + str(self.phone_number)


# Customers Database...
class Customers(models.Model):

    # Customer Personals...
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    customer_id = models.CharField(max_length=10, blank=False)
    contact_details = models.OneToOneField(ContactDetails, on_delete=models.CASCADE)
    gender = models.CharField(choices=gender_options, max_length=10)

    # Number of visits...
    number_of_visits = models.IntegerField(default=0)

    class Meta:
        db_table = "Customers Details"
        order_with_respect_to = 'customer_id'

    def __str__(self):
        return self.user.username


# Notified Emails...
class NotifiedEmails(models.Model):
    email = models.EmailField(unique=True)

    class Meta:
        db_table = 'Emails to be notified'

    def __str__(self):
        return self.email

HotelManagement/Customers/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from RoomService import models as rs_models
from . import models as customer_models
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib import messages
from . import decoraters
from django.core.mail import EmailMessage, send_mail


# Landing Page...
@decoraters.user_not_logged_in
def landing_page(request):
    # Counting total number of Customers...
    number_of_customers = 0

    for user in User.objects.all():
        if hasattr(user, 'customers'):
            number_of_customers += 1
    # .....................................

    # Counting total number of Employees...
    number_of_employees = 0

    for user in User.objects.all():
        if not hasattr(user, 'customers'):
            number_of_employees += 1
    # .....................................

    # Counting total number of blocks...
    number_of_blocks = 0
    blocks = []

    for block in rs_models.BlockFloor.objects.values_list('block'):
        if block not in blocks:
            blocks.append(block)
            number_of_blocks += 1
        else:
            pass
    # .....................................

    # Counting total number of rooms...
    number_of_rooms = 0

    for room in rs_models.Room.objects.all():
        number_of_rooms += 1

    # .....................................

    args = {'customers_count': number_of_customers, 'blocks_count': number_of_blocks, 'rooms_count': number_of_rooms,
            'employees_count': number_of_employees}
    return render(request, 'customers/landing_page.html', args)


@decoraters.user_login_required
@decoraters.is_customer
def home(request):
    # Checking if any rooms were booked by current User...
    booked_rooms = 0
    for booked_user in rs_models.Room.objects.values_list('booked_customer__user'):
        if request.user.id == booked_user[0]:
            booked_rooms += 1

    email = customer_models.Customers.objects.get(user=request.user).contact_details.email

    username = request.user.username
    args = {'username': username, 'rooms_booked': booked_rooms, 'email': email}
    return render(request, 'customers/home.html', args)


# Adding Email to Notifications...
@decoraters.user_login_required
def add_email(request, email):
    added_email = customer_models.NotifiedEmails.objects.create(email=email)
    added_email.save()

    messages.success(request, f'From now you will receive notifications from our website')

    return redirect('customers:home')


# Customers Authentication..............................................................................................

# Customer Login...
@decoraters.user_not_logged_in
def customer_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            user_inst = User.objects.get(username=username)
            if hasattr(user_inst, 'customers'):

                if user.is_active:
                    login(request, user)
                    return redirect('customers:home')
                else:
                    return HttpResponse('account not active')

            else:
                messages.error(request, f'Invalid Login details')

        else:
            messages.error(request, f'Invalid Login details')

        return redirect(reverse('customers:login'))

    else:
        return render(request, 'customers/login.html')


# Customer Logout...
@decoraters.user_login_required
def customer_logout(request):
    logout(request)
    return redirect('customers:landing_page')

# ......................................................................................................................


# Management Login...
@decoraters.user_not_logged_in
def management_login_page(request):
    return render(request, 'customers/management_login.html')

HotelManagement/templates/customers/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    {% block head %}{% endblock head %}

</head>
<body>

    {% block body %}{% endblock body %}

</body>
</html>

HotelManagement/templates/customers/login.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>

<head>
	<title>REST IN - LOGIN</title>

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<meta name="keywords" content="Tool Sign In Form a Responsive Web Template, Bootstrap Web Templates, Flat Web Templates, Android Compatible Web Template, Smartphone Compatible Web Template, Free Webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design">
	<script>
		addEventListener("load", function () {
			setTimeout(scrollTop, 0);
		}, false);

		function scrollTop() {
			window.scrollTo(0, 1);
		}
	</script>

	<link href="{% static 'customers/login/css/style.css' %}" rel='stylesheet' type='text/css' />

	<link href="//fonts.googleapis.com/css?family=Poiret+One&amp;subset=cyrillic,latin-ext" rel="stylesheet">

</head>

<body>
    <div class="page-overlay"></div>
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-warning" style="text-align: center; position: absolute; width: 100%; top: 69px">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-success" style="text-align: center; position: absolute; width: 100%; top: 69px">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
	<h1>Customer Login </h1>
	<div class="w3ls-login box box--big">

		<form method="post">
            {% csrf_token %}
			<div class="agile-field-txt">
				<label> Username</label>
				<input type="text" name="username" placeholder="Enter User Name"
                       oninvalid="this.setCustomValidity('Username is required')"
                               oninput="this.setCustomValidity('')" required="" />
			</div>
			<div class="agile-field-txt">
				<label> password</label>
				<input type="password" name="password" placeholder="Enter Password" required="" id="password" />
				<div class="agile_label">
					<input id="check3" name="check3" type="checkbox" value="show password" onclick="show_password()">
					<label class="check" for="check3">Show password</label>
				</div>
				<div class="agile-right">
					<a href="#">forgot password?</a>
				</div>
			</div>

			<div class="w3ls-bot">
				<div class="switch-agileits">
					<label class="switch">
						<input type="checkbox">
						<span class="slider round"></span>
						keep me signed in
					</label>
				</div>
			</div>
				<input type="submit" value="LOG IN">
		</form>
	</div>

</body>
</html>

HotelManagement/templates/customers/management_login.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>REST IN - Management</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

    <a href="{% url 'rooms_management:login' %}" class="btn btn-outline-primary rm_mng_log mt-5 ml-5">Room Management Login</a>
    <a href="{% url 'food_management:login' %}" class="btn btn-outline-secondary fd_mng_log mt-5 ml-5">Food Management Login</a>

    {#  Bootstrap JS  #}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>